### ISSUE TITLE
输出层

### ISSUE THREAD

**Issue by dongli96** [yjh126yjh/TianChi_Protein-Secondary-Structure-Prediction#3]
请问最后的卷积层的输出是700*8（共5600个神经元），为什么能作为整个CNN的输出层？输出层应该是8个神经元吧。

**Comment by njzjz** [comment]
输出层在这里，就是8。
https://github.com/yjh126yjh/TianChi_Protein-Secondary-Structure-Prediction/blob/9398db9b960436fc638d9994635adba6ada474f0/model.py#L54

700是数据的大小。

**Comment by yjh126yjh** [comment]
是8类没错，可是要考虑一整条序列长700。并不是输入一条序列，分成8类，而是这个序列每个氨基酸都分成8类。
